services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 9090:3000
    volumes:
      - ./docuseal:/data/docuseal
      - ./lib/docuseal.rb:/app/lib/docuseal.rb
      - ./app/controllers/esign_settings_controller.rb:/app/app/controllers/esign_settings_controller.rb
    environment:
      - RAILS_ENV=production
      - FORCE_SSL=${HOST}
      - ADVANCED_FORMATS=true
      - APP_URL=https://trustseal.cybroscloud.com
      - DATABASE_URL=postgresql://postgres:1122@host.docker.internal:5432/docuseal
    extra_hosts:
      - 'host.docker.internal:host-gateway'
