services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9090:3000
    volumes:
      - ./docuseal:/data/docuseal
      - ./lib/docuseal.rb:/app/lib/docuseal.rb
      - ./app/controllers/esign_settings_controller.rb:/app/app/controllers/esign_settings_controller.rb
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
    extra_hosts:
      - 'host.docker.internal:host-gateway'
